- Duplicate dhclient-script updates for DHCPv6 to all provided scripts.   [ISC-Bugs #16875]

diff --git a/client/scripts/freebsd b/client/scripts/freebsd
--- a/client/scripts/freebsd
+++ b/client/scripts/freebsd
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: freebsd,v 1.17 2006/07/22 02:24:16 dhankins Exp $
+# $Id: freebsd,v 1.18 2007/05/18 17:18:05 dhankins Exp $
 #
 # $FreeBSD$
 
@@ -42,6 +42,33 @@ make_resolv_conf() {
       fi
 
       if [ $exit_status -ne 0 ]; then
+	$LOGGER "Error while writing new /etc/resolv.conf."
+      fi
+    fi
+  elif [ "x${new_dhcp6_name_servers}" != x ] ; then
+    ( cat /dev/null > /etc/resolv.conf.dhclient6 )
+    exit_status=$?
+    if [ $exit_status -ne 0 ] ; then
+      $LOGGER "Unable to create /etc/resolv.conf.dhclient6: Error $exit_status"
+    else
+      if [ "x${new_dhcp6_domain_search}" != x ] ; then
+	( echo search ${new_dhcp6_domain_search} >> /etc/resolv.conf.dhclient6 )
+	exit_status=$?
+      fi
+      for nameserver in ${new_dhcp6_name_servers} ; do
+	if [ $exit_status -ne 0 ] ; then
+	  break
+	fi
+        ( echo nameserver ${nameserver} >> /etc/resolv.conf.dhclient6 )
+	exit_status = $?
+      done
+
+      if [ $exit_status -ne 0 ] ; then
+        ( mv /etc/resolv.conf.dhclient6 /etc/resolv.conf )
+	exit_status = $?
+      fi
+
+      if [ $exit_status -ne 0 ] ; then
 	$LOGGER "Error while writing new /etc/resolv.conf."
       fi
     fi
@@ -96,6 +123,10 @@ if [ x$reason = xMEDIUM ]; then
   sleep 1
   exit_with_hooks 0
 fi
+
+###
+### DHCPv4 Handlers
+###
 
 if [ x$reason = xPREINIT ]; then
   if [ x$alias_ip_address != x ]; then
@@ -251,6 +282,66 @@ if [ x$reason = xTIMEOUT ]; then
   arp -n -a | sed -n -e 's/^.*(\(.*\)) at .*$/arp -d \1/p' \
 							|sh >/dev/null 2>&1
   exit_with_hooks 1
+fi
+
+###
+### DHCPv6 Handlers
+###
+
+if [ ${reason} = PREINIT6 ] ; then
+  # Ensure interface is up.
+  ifconfig ${interface} up
+
+  # XXX: Remove any stale addresses from aborted clients.
+
+  exit_with_hooks 0
+fi
+
+if [ ${reason} = BOUND6 ] ; then
+  if [ x${new_ip6_address} = x ] || [ x${new_ip6_prefixlen} = x ] ; then
+    exit_with_hooks 2;
+  fi
+
+  ifconfig ${interface} inet6 alias ${new_ip6_address}/${new_ip6_prefixlen}
+
+  # Check for nameserver options.
+  make_resolv_conf
+
+  exit_with_hooks 0
+fi
+
+if [ ${reason} = RENEW6 ] || [ ${reason} = REBIND6 ] ; then
+  # Make sure nothing has moved around on us.
+
+  # Nameservers/domains/etc.
+  if [ "x${new_dhcp6_name_servers}" != "x${old_dhcp6_name_servers}" ] ||
+     [ "x${new_dhcp6_domain_search}" != "x${old_dhcp6_domain_search}" ] ; then
+    make_resolv_conf
+  fi
+
+  exit_with_hooks 0
+fi
+
+if [ ${reason} = DEPREF6 ] ; then
+  if [ x${new_ip6_prefixlen} = x ] ; then
+    exit_with_hooks 2;
+  fi
+
+  # XXX:
+  # There doesn't appear to be a way to update an addr to indicate
+  # preference.
+
+  exit_with_hooks 0
+fi
+
+if [ ${reason} = EXPIRE6 ] ; then
+  if [ x${old_ip6_address} = x ] || [ x${old_ip6_prefixlen} = x ] ; then
+    exit_with_hooks 2;
+  fi
+
+  ifconfig ${interface} inet6 -alias ${old_ip6_address}/${old_ip6_prefixlen}
+
+  exit_with_hooks 0
 fi
 
 exit_with_hooks 0
